/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.panel;

import javax.swing.JButton;

/**
 *
 * @author Rizal
 */
public final class PanelTombol extends javax.swing.JPanel {

    /**
     * Creates new form PanelTombol
     */
    public PanelTombol() {
        initComponents();Terpilih(false);
    }
    
    public void Disable(){
        btnNew.setEnabled(false);btnView.setEnabled(false);
        btnEdit.setEnabled(false);btnDelete.setEnabled(false);
        btnCancel.setEnabled(false);     
    }
    
    public void invis(){
        btnView.setVisible(false);
        btnEdit.setVisible(false);btnDelete.setVisible(false);
        btnCancel.setVisible(false);
    }
    
    public void Terpilih(boolean c){
        btnNew.setEnabled(!c);btnView.setEnabled(c);
        btnEdit.setEnabled(c);btnDelete.setEnabled(c);        
        btnCancel.setEnabled(c);
    }
    
    public JButton getBtnNew(){
        return this.btnNew;
    }
    
    public JButton getBtnView(){
        return this.btnView;
    }
    
    public JButton getBtnEdit(){
        return this.btnEdit;
    }
    
    public JButton getBtnDelete(){
        return this.btnDelete;
    }
    
    public JButton getBtnCancel(){
        return this.btnCancel;
    }
    
    public JButton getBtnExit(){
        return this.btnExit;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        btnNew.setText(org.openide.util.NbBundle.getMessage(PanelTombol.class, "PanelTombol.btnNew.text")); // NOI18N

        btnEdit.setText(org.openide.util.NbBundle.getMessage(PanelTombol.class, "PanelTombol.btnEdit.text")); // NOI18N

        btnDelete.setText(org.openide.util.NbBundle.getMessage(PanelTombol.class, "PanelTombol.btnDelete.text")); // NOI18N

        btnExit.setText(org.openide.util.NbBundle.getMessage(PanelTombol.class, "PanelTombol.btnExit.text")); // NOI18N

        btnView.setText(org.openide.util.NbBundle.getMessage(PanelTombol.class, "PanelTombol.btnView.text")); // NOI18N

        btnCancel.setText(org.openide.util.NbBundle.getMessage(PanelTombol.class, "PanelTombol.btnCancel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(btnExit))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnNew)
                .addComponent(btnEdit)
                .addComponent(btnDelete)
                .addComponent(btnView)
                .addComponent(btnCancel))
            .addComponent(btnExit)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnView;
    // End of variables declaration//GEN-END:variables
}
