/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.transaksi.dialog;

import com.voting.model.master.Tps;
import com.voting.model.transaksi.Bilik;
import com.voting.service.TransactionService;
import com.voting.ui.frame.MainUi;
import javax.swing.JOptionPane;
import javax.swing.JDialog;
/**
 *
 * @author Rizal
 */
public class BilikDialog extends JDialog {
    
    TransactionService ts = MainUi.getTransactionService();
    Bilik bilik;
    Tps tps;

    /**
     * Creates new form LogIn
     * @param parent
     * @param modal
     */
    public BilikDialog() {
        super(MainUi.getInstance(), true);
        tps = MainUi.getTps();initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNo = new javax.swing.JLabel();
        lTps = new javax.swing.JLabel();
        lTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bOk = new javax.swing.JButton();
        cNo = new javax.swing.JComboBox<>();
        tpsCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin Log In");

        lNo.setText(org.openide.util.NbBundle.getMessage(BilikDialog.class, "BilikDialog.lNo")); // NOI18N

        lTps.setText(org.openide.util.NbBundle.getMessage(BilikDialog.class, "BilikDialog.lTps")); // NOI18N

        lTitle.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText(org.openide.util.NbBundle.getMessage(BilikDialog.class, "BilikDialog.lTitle")); // NOI18N

        bOk.setText(org.openide.util.NbBundle.getMessage(BilikDialog.class, "BilikDialog.bOk")); // NOI18N
        bOk.setActionCommand(org.openide.util.NbBundle.getMessage(BilikDialog.class, "BilikDialog.bOk")); // NOI18N
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eLogin(evt);
            }
        });

        cNo.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] { 1,2,3,4,5,6,7,8,9,10 }));

        tpsCode.setText(tps.getCode());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bOk))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTps)
                            .addComponent(lNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tpsCode, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNo)
                    .addComponent(cNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTps)
                    .addComponent(tpsCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bOk)
                .addContainerGap())
        );

        cNo.setSelectedItem(null);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eLogin
        if(validateForm()){
            Bilik b=ts.cekBilik((Integer) cNo.getSelectedItem(), tps);
            if(b==null){                
                bilik=new Bilik((Integer) cNo.getSelectedItem(),tps);
                bilik.setStatus(1);
                ts.saveBilik(bilik);
                dispose();
            } else{
                if(b.getStatus()==0){
                    b.setStatus(1);bilik=b;
                    ts.updateBilik(bilik);
                    dispose();
                } else{
                    JOptionPane.showMessageDialog(MainUi.getInstance(), "Bilik Sudah Ada!");
                }
            }
        }
    }//GEN-LAST:event_eLogin
    public boolean validateForm(){
        if(cNo.getSelectedItem() == null){
            JOptionPane.showMessageDialog(MainUi.getInstance(), "Nomor Bilik tidak boleh kosong!");
            return false;
        }
        return true;
    }    
    public Bilik getBilik() {
        setVisible(true);
        return bilik;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOk;
    private javax.swing.JComboBox<Integer> cNo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lNo;
    private javax.swing.JLabel lTitle;
    private javax.swing.JLabel lTps;
    private javax.swing.JTextField tpsCode;
    // End of variables declaration//GEN-END:variables
}
