/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.transaksi.dialog;

import com.voting.model.master.Pemilih;
import com.voting.model.master.Tps;
import com.voting.model.transaksi.Bilik;
import com.voting.service.TransactionService;
import com.voting.ui.frame.MainUi;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.JDialog;
import javax.swing.Timer;
/**
 *
 * @author Rizal
 */
public class Unavailable extends JDialog {
    
    TransactionService ts = MainUi.getTransactionService();
    Pemilih pemilih;
    Bilik bilik;
    Tps tps;

    /**
     * Creates new form LogIn
     * @param parent
     * @param modal
     */
    public Unavailable() {
        super(MainUi.getInstance(), true);
        tps = MainUi.getTps();bilik = MainUi.getBilik();
        initComponents();check();setLocationRelativeTo(null);
    }
    public void check(){
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        Timer timer = new Timer(1, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Bilik b=ts.cekBilik(bilik.getNo(), tps);
                pemilih=b.getIdPemilih();
                if(pemilih!=null){
                    bilik=b;dispose();
                } else {
                    check();
                }
            }
        });
        timer.setRepeats(false);
        timer.start();// </editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ico = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lTitle = new javax.swing.JLabel();
        sep = new javax.swing.JSeparator();
        lText1 = new javax.swing.JLabel();
        lText2 = new javax.swing.JLabel();
        lText3 = new javax.swing.JLabel();
        bOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin Log In");

        ico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lTitle.setFont(new java.awt.Font("Futured", 1, 16)); // NOI18N
        lTitle.setText(org.openide.util.NbBundle.getMessage(Unavailable.class, "Unavailable.lTitle")); // NOI18N

        lText1.setText(org.openide.util.NbBundle.getMessage(Unavailable.class, "Unavailable.lText1")); // NOI18N

        lText2.setText(org.openide.util.NbBundle.getMessage(Unavailable.class, "Unavailable.lText2")); // NOI18N

        lText3.setText(org.openide.util.NbBundle.getMessage(Unavailable.class, "Unavailable.lText3")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sep, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lText2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lText3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lText3)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        bOk.setText(org.openide.util.NbBundle.getMessage(Unavailable.class, "BilikDialog.bOk")); // NOI18N
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eOk(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ico, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bOk)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eOk(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eOk
        dispose();
    }//GEN-LAST:event_eOk
    public Bilik getBilik() {
        setVisible(true);
        return bilik;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOk;
    private javax.swing.JLabel ico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lText1;
    private javax.swing.JLabel lText2;
    private javax.swing.JLabel lText3;
    private javax.swing.JLabel lTitle;
    private javax.swing.JSeparator sep;
    // End of variables declaration//GEN-END:variables
}
