/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.frame.dialog;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.ResourceBundle;

import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamResolution;
import com.voting.ui.frame.MainUi;

/**
 *
 * @author Rizal
 */
public class CamOptionDialog extends javax.swing.JDialog {

    public static final int RET_CANCEL = 2;
    public static final int RET_OK = 0;

    private final ResourceBundle bundle = ResourceBundle.getBundle("com.voting.ui.frame.dialog.Bundle");
    private Webcam capture;
    private Webcam scanner;
    private WebcamResolution cSize;

    /**
     * Creates new form CamOptionDialog
     */
    public CamOptionDialog() {
        super(MainUi.getInstance(), true);
        initComponents();
        // <editor-fold defaultstate="collapsed" desc="Compiled Code Key Listener">
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });// </editor-fold>
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        this.setVisible(true);
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings({"CollectionsToArray", "Convert2Diamond"})
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lCapture = new javax.swing.JLabel();
        cCapture = new javax.swing.JComboBox<>();
        lScanner = new javax.swing.JLabel();
        cScanner = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        sCapture = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setTitle(bundle.getString("CamOptionDialog.title")); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(360, 195));
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                doClose(RET_CANCEL);
            }
        });

        btnOk.setText(bundle.getString("CamOptionDialog.btnOk.text")); // NOI18N
        btnCancel.setText(bundle.getString("CamOptionDialog.btnCancel.text")); // NOI18N

        btnOk.addActionListener(e -> eOk());
        btnCancel.addActionListener(e -> doClose(RET_CANCEL));

        lTitle.setFont(new java.awt.Font("Futured", 1, 24)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText(bundle.getString("CamOptionDialog.lTitle.text")); // NOI18N

        lCapture.setText(bundle.getString("CamOptionDialog.lCapture.text")); // NOI18N

        List<Webcam> capt = Webcam.getWebcams();
        cCapture.setModel(new DefaultComboBoxModel<Webcam>(capt.toArray(new Webcam[0])));

        lScanner.setText(bundle.getString("CamOptionDialog.lScanner.text")); // NOI18N

        List<Webcam> scan = Webcam.getWebcams();
        cScanner.setModel(new DefaultComboBoxModel<Webcam>(scan.toArray(new Webcam[0])));

        sCapture.setModel(new DefaultComboBoxModel<>(WebcamResolution.values()));

        jLabel1.setText(bundle.getString("CamOptionDialog.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addComponent(jSeparator2)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lScanner)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cScanner, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCancel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lCapture)
                                                        .addComponent(jLabel1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(sCapture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cCapture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{btnCancel, btnOk});

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lCapture)
                                        .addComponent(cCapture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sCapture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cScanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lScanner))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCancel)
                                        .addComponent(btnOk))
                                .addContainerGap())
        );

        getRootPane().setDefaultButton(btnOk);
        cCapture.setSelectedItem(MainUi.getCaptureCam());
        cScanner.setSelectedItem(MainUi.getQrCam());
        sCapture.setSelectedItem(MainUi.getCaptureSize());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eOk() {//GEN-FIRST:event_eOk
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        capture = (Webcam) cCapture.getSelectedItem();
        scanner = (Webcam) cScanner.getSelectedItem();
        cSize = (WebcamResolution) sCapture.getSelectedItem();
        MainUi.setCaptureSize(cSize);
        MainUi.setDefaultDimensions(setDimen());
        MainUi.setCaptureCam(capture);
        MainUi.setQrCam(scanner);
        doClose(RET_OK);// </editor-fold>
    }//GEN-LAST:event_eOk

    private void doClose(int retStatus) {
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        returnStatus = retStatus;
        setVisible(false);
        dispose();// </editor-fold>
    }

    private Dimension[] setDimen() {
        WebcamResolution[] r = WebcamResolution.values();
        Dimension[] a = new Dimension[r.length];
        int i = 0;
        for (WebcamResolution w : WebcamResolution.values()) {
            a[i] = w.getSize();
            i++;
        }
        return a;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<Webcam> cCapture;
    private javax.swing.JComboBox<Webcam> cScanner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lCapture;
    private javax.swing.JLabel lScanner;
    private javax.swing.JLabel lTitle;
    private javax.swing.JComboBox<WebcamResolution> sCapture;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
