/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.frame.dialog;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.voting.ui.frame.MainUi;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import javax.swing.JDialog;

/**
 *
 * @author Rizal
 */
public class CaptureDialog extends JDialog implements ActionListener {

    /**
     * Creates new form Capture 
     * @param parent
     */
    
    public CaptureDialog(Frame parent){
        super(parent,true);
        initComponents();
    }
    private Webcam webcam;
    BufferedImage image;
    WebcamPanel panel;
    Dimension size;

    @Override
    public void actionPerformed(ActionEvent ae) {
        image=webcam.getImage();doClose();
    }
    
    public BufferedImage getImage(){
        this.setVisible(true);
        if(image!=null){
            Rectangle crop = rect(image, 3, 4);
            BufferedImage img = image.getSubimage(crop.x, crop.y, crop.width, crop.height); //fill in the corners of the desired crop location here
            BufferedImage copyOfImage = new BufferedImage(img.getWidth(), img.getHeight(), BufferedImage.TYPE_INT_RGB);
            Graphics g = copyOfImage.createGraphics();
            g.drawImage(img, 0, 0, null);
            g.dispose();
            return copyOfImage;
        }
        return image;//or use it however you want
    }
    
    private Rectangle rect(BufferedImage img, int rX, int rY){
        int y=img.getHeight(),w=img.getWidth();
        int w2=((rX*y)/rY),w3=w-w2;
        int x1=(w3/2),x2=w-w3;
        
        return new Rectangle(x1,0,x2,y);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTengah = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Capture Photo - Local Electronic Voting");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                exit(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pTengah.setLayout(new java.awt.GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbc.fill = GridBagConstraints.HORIZONTAL;

        webcam = MainUi.getCaptureCam();
        webcam.setCustomViewSizes(MainUi.getDimensions());
        size = MainUi.getCaptureSize().getSize();
        webcam.setViewSize(size);
        panel = new WebcamPanel(webcam);
        panel.setFPSDisplayed(false);
        panel.setFillArea(true);
        panel.setDisplayDebugInfo(false);
        panel.setImageSizeDisplayed(true);
        panel.setMirrored(false);

        javax.swing.JPanel button = new javax.swing.JPanel();
        button.setPreferredSize(new java.awt.Dimension(70, 40));

        pTengah.add(panel, gbc);
        pTengah.add(button, gbc);

        javax.swing.JButton capture = new javax.swing.JButton();
        capture.setText("Capture");
        capture.addActionListener(this);
        button.add(capture, gbc);
        getContentPane().add(pTengah, new java.awt.GridBagConstraints());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exit
        doClose();
    }//GEN-LAST:event_exit
    
    private void doClose() {
        webcam.close();
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pTengah;
    // End of variables declaration//GEN-END:variables
}
