/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.frame.dialog;

import java.awt.Frame;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import javafx.animation.Timeline;
import javax.swing.JDialog;
import org.openide.util.Exceptions;
/**
 *
 * @author Rizal
 */
public class GetServer extends JDialog {
    static String[] p=new String[4];
    static List<InetAddress> ips = new ArrayList();
    static InetAddress ip;
    static String server,dir;
    Timeline updater;
    
    /**
     * Creates new form LogIn
     * @param parent
     * @param modal
     */
    public GetServer(Frame parent) {
        super(parent, true);
        initComponents();loadData();
        setLocationRelativeTo(null);
    }
    
    private static void loadData(){
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        try{
            InetAddress addr = InetAddress.getLocalHost();
            String l = addr.getHostAddress();
            p = l.split("\\.");
        } catch (UnknownHostException ex) {
            System.out.println("Hostname can not be resolved");
        }
        int timeout=3000;String host=p[0]+"."+p[1]+"."+p[2]+".1";
        try {
            if (InetAddress.getByName(host).isReachable(timeout)){
                InetAddress addr = InetAddress.getByName(host);
                rClient.setText(addr.getHostAddress());
            }
        } catch (UnknownHostException ex) {
            Exceptions.printStackTrace(ex);
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }// </editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mode = new javax.swing.ButtonGroup();
        lTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnSlc = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        rServer = new javax.swing.JRadioButton();
        rClient = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Select Server");
        setResizable(false);

        lTitle.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText(org.openide.util.NbBundle.getMessage(GetServer.class, "GetServer.lTitle.text")); // NOI18N

        btnSlc.setText(org.openide.util.NbBundle.getMessage(GetServer.class, "GetTPS.btnLogin.text")); // NOI18N
        btnSlc.setEnabled(false);
        btnSlc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSelect(evt);
            }
        });

        btnExit.setText(org.openide.util.NbBundle.getMessage(GetServer.class, "GetTPS.btnExit.text")); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eExit(evt);
            }
        });

        Mode.add(rServer);
        rServer.setText("Localhost");
        rServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                click(evt);
            }
        });

        Mode.add(rClient);
        rClient.setText("Client (Select Server From Table)");
        rClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                click(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rServer)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSlc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExit))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(rClient)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSlc)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void eExit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eExit
        System.exit(0);
    }//GEN-LAST:event_eExit

    private void eSelect(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSelect
        createProp();dispose();
    }//GEN-LAST:event_eSelect

    private void click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_click
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        javax.swing.JRadioButton b=(javax.swing.JRadioButton) evt.getSource();
        btnSlc.setEnabled(true);System.out.println(b.getText());
        if(b.equals(rServer)){
            server="127.0.0.1";
        } else{
            server=b.getText();
        }// </editor-fold>
    }//GEN-LAST:event_click
    public String getServer(String d) {
        dir = d;setVisible(true);
        return server;
    }
    
    private void createProp(){
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        Properties props = new Properties();
        try (FileInputStream in = new FileInputStream("/jdbc.properties")) {
            props.load(in);
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
        try (FileOutputStream out = new FileOutputStream(dir)) {
            props.setProperty("jdbc.ip", server);
            props.setProperty("jdbc.dbase", "voting");
            props.store(out, null);
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }// </editor-fold>
    }   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Mode;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSlc;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lTitle;
    private static javax.swing.JRadioButton rClient;
    private static javax.swing.JRadioButton rServer;
    // End of variables declaration//GEN-END:variables
}
