/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.frame.dialog;

import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import javax.swing.JDialog;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.AbstractTableModel;

import com.voting.model.master.Tps;
import com.voting.ui.frame.MainUi;

/**
 *
 * @author Rizal
 */
public class GetTPS extends JDialog {

    private static List<Tps> tpss;
    private final ResourceBundle bundle = ResourceBundle.getBundle("com.voting.ui.frame.dialog.Bundle");
    Tps tps;

    /**
     * Creates new form LogIn
     *
     * @param parent
     * @param modal
     */
    public GetTPS(Frame parent) {
        super(parent, true);
        initComponents();
        initListener();
        loadData();
        setLocationRelativeTo(null);
    }

    private void initListener() {
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        tData.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (tData.getSelectedRow() >= 0) {
                int indexModel = tData.convertRowIndexToModel(tData.getSelectedRow());
                tps = tpss.get(indexModel);
            }
        });// </editor-fold>
    }

    private static void loadData() {
        tpss = MainUi.getMasterService().getAllTps();
        tData.setModel(new TpsModel(tpss));
    }

    private static class TpsModel extends AbstractTableModel {

        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        private List<Tps> tpsModel = new ArrayList<>();

        public TpsModel(List<Tps> tpsModel) {
            this.tpsModel = tpsModel;
            fireTableDataChanged();
        }

        @Override
        public int getRowCount() {
            return tpsModel.size();
        }

        @Override
        public int getColumnCount() {
            return 8;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Tps t = tpsModel.get(rowIndex);
            return switch (columnIndex) {
                case 0 ->
                    t.getCode();
                case 1 ->
                    "<HTML>" + t.getDesk().replaceAll("\n", " ") + "</HTML>";
                default ->
                    "";
            };
        }// </editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        sType = new javax.swing.JComboBox<>();
        iForm = new javax.swing.JTextField();
        bRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin Log In");
        setResizable(false);

        lTitle.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText(bundle.getString("GetTPS.lTitle.text")); // NOI18N

        btnLogin.setText(bundle.getString("GetTPS.btnLogin.text")); // NOI18N
        btnLogin.addActionListener(e -> dispose());

        btnExit.setText(bundle.getString("GetTPS.btnExit.text")); // NOI18N
        btnExit.addActionListener(e -> dispose());

        sType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Provinsi", "Kabupaten", "Kecamatan", "Desa/Kelurahan", "Kode TPS", "Deskripsi"}));
        sType.addActionListener(e -> search());

        iForm.addActionListener(e -> search());
        iForm.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search();
            }
        });

        bRefresh.setText(bundle.getString("GetTPS.bRefresh.text")); // NOI18N
        bRefresh.addActionListener(e -> refresh());

        tData.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Kode TPS", "Deskripsi"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                true, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(tData);
        if (tData.getColumnModel().getColumnCount() > 0) {
            tData.getColumnModel().getColumn(0).setMinWidth(120);
            tData.getColumnModel().getColumn(0).setMaxWidth(120);
            tData.getColumnModel().getColumn(1).setResizable(false);
        }
        tData.setAutoCreateColumnsFromModel(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnLogin)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                                                .addComponent(btnExit))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(sType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(iForm)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bRefresh)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(iForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bRefresh))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnLogin)
                                        .addComponent(btnExit))
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void refresh() {
        iForm.setText(null);
        sType.setSelectedIndex(0);
        loadData();
    }

    public Tps getTps() {
        setVisible(true);
        return tps;
    }

    private void search() {
        tpss = MainUi.getMasterService().searchTps(sType.getSelectedIndex(), iForm.getText());
        tData.setModel(new TpsModel(tpss));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private static javax.swing.JTextField iForm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lTitle;
    private static javax.swing.JComboBox<String> sType;
    private static javax.swing.JTable tData;
    // End of variables declaration//GEN-END:variables
}
