/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.frame.dialog;

import java.util.ResourceBundle;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import com.twmacinta.util.MD5;
import com.voting.model.security.Admin;
import com.voting.ui.frame.MainUi;

/**
 *
 * @author Rizal
 */
public class InputPass extends JDialog {

    private final ResourceBundle bundle = ResourceBundle.getBundle("com.voting.ui.frame.dialog.Bundle");

    boolean res = false;

    /**
     * Creates new form LogIn
     *
     * @param parent
     * @param modal
     */
    public InputPass() {
        super(MainUi.getInstance(), true);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lPass = new javax.swing.JLabel();
        fPass = new javax.swing.JPasswordField();
        lTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin Log In");

        lPass.setText(bundle.getString("InputPass.lPass.text")); // NOI18N

        fPass.addActionListener(e -> eLogin());

        lTitle.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText(bundle.getString("InputPass.lTitle.text")); // NOI18N

        btnLogin.setText(bundle.getString("InputPass.btnLogin.text")); // NOI18N
        btnLogin.addActionListener(e -> eLogin());

        btnExit.setText(bundle.getString("InputLogin.btnExit.text")); // NOI18N
        btnExit.addActionListener(e -> dispose());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator1)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lPass)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(fPass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnLogin)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                                .addComponent(btnExit)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lPass)
                                        .addComponent(fPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnLogin)
                                        .addComponent(btnExit))
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // @SuppressWarnings("unused")
    private void eLogin() {//GEN-FIRST:event_eLogin
        if (validateForm()) {
            Admin a = MainUi.getAdmin();
            String password = new MD5(new String(fPass.getPassword())).asHex();
            if (a.getPassword().equals(password)) {
                res = true;
                dispose();
            } else {
                JOptionPane.showMessageDialog(MainUi.getInstance(), "Kata Sandi tidak cocok!");
            }
        }
    }//GEN-LAST:event_eLogin

    public boolean validateForm() {
        if (fPass.getPassword() == null || fPass.getPassword().length == 0) {
            JOptionPane.showMessageDialog(MainUi.getInstance(), "Kata Sandi tidak boleh kosong!");
            return false;
        }
        return true;
    }

    public boolean logout() {
        setVisible(true);
        return res;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField fPass;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lPass;
    private javax.swing.JLabel lTitle;
    // End of variables declaration//GEN-END:variables
}
