/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.transaksi;

import com.voting.model.master.Calon;
import com.voting.model.master.Pemilih;
import com.voting.model.transaksi.Bilik;
import com.voting.service.MasterService;
import com.voting.service.TransactionService;
import com.voting.ui.frame.MainUi;
import com.voting.ui.panel.CalonInfo;
import com.voting.ui.transaksi.dialog.BilikDialog;
import com.voting.ui.transaksi.dialog.Unavailable;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Rizal
 */
public class BilikPanel extends javax.swing.JInternalFrame {
    TransactionService ts=MainUi.getTransactionService();
    MasterService ms=MainUi.getMasterService();
    List<Calon> calons;
    Pemilih pemilih;
    Bilik bilik;

    /**
     * Creates new form BilikPanel
     */
    public BilikPanel() {
        initComponents();
        setBilik();check();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBilik = new javax.swing.JPanel();
        lTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pCard = new javax.swing.JPanel();
        lNIK = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();

        setTitle(org.openide.util.NbBundle.getMessage(BilikPanel.class, "BilikPanel.title")); // NOI18N

        lTitle.setFont(new java.awt.Font("Futured", 1, 24)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText(org.openide.util.NbBundle.getMessage(BilikPanel.class, "BilikPanel.lTitle.text")); // NOI18N

        pCard.setLayout(new java.awt.GridBagLayout());

        lNIK.setFont(new java.awt.Font("Futured", 0, 14)); // NOI18N
        lNIK.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lNIK.setText(org.openide.util.NbBundle.getMessage(BilikPanel.class, "BilikPanel.lNIK.text")); // NOI18N

        lNama.setFont(new java.awt.Font("Futured", 0, 14)); // NOI18N
        lNama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lNama.setText(org.openide.util.NbBundle.getMessage(BilikPanel.class, "BilikPanel.lNama.text")); // NOI18N

        javax.swing.GroupLayout pBilikLayout = new javax.swing.GroupLayout(pBilik);
        pBilik.setLayout(pBilikLayout);
        pBilikLayout.setHorizontalGroup(
            pBilikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBilikLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBilikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(pCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBilikLayout.createSequentialGroup()
                        .addComponent(lNIK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pBilikLayout.setVerticalGroup(
            pBilikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBilikLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pCard, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pBilikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNama)
                    .addComponent(lNIK))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBilik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBilik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setBilik(){
        bilik=new BilikDialog().getBilik();
        MainUi.setBilik(bilik);
        lTitle.setText("Bilik No: "+bilik.getNo());
    }
    
    private void check(){
        pemilih=bilik.getIdPemilih();
        setPemilih(pemilih);
        if(pemilih==null){
            bilik=new Unavailable().getBilik();
            MainUi.setBilik(bilik);
            check();
        }
    }
    
    private void loadData(){
        calons=ms.getAllCalon();
        for(Calon c : calons){
            javax.swing.JPanel i=new CalonInfo(c);
            i.addMouseListener(new MouseAdapter(){
                @Override
                public void mousePressed(MouseEvent me) {
                    int Pilih = JOptionPane.showConfirmDialog(MainUi.getInstance(),"Apakah anda yakin akan memilih "+c.getNama()+"?","Konfirmasi",JOptionPane.YES_NO_OPTION);
                    if(Pilih == JOptionPane.YES_OPTION){
                        c.setSuara(c.getSuara()+1);pemilih.setKet(1);
                        bilik.setSuara(bilik.getSuara()+1);
                        ts.pilihCalon(pemilih,c,bilik);
                        JOptionPane.showMessageDialog(MainUi.getInstance(),"Teimakasih Sudah Memberikan Suara!");
                        done();
                    }
                } 
            });
            pCard.add(i);
        }
    }
    
    private void setPemilih(Pemilih p){
        if(p!=null){
            loadData();pCard.setVisible(true);
            lNIK.setText(p.getInduk());
            lNama.setText(p.getNama());
        } else{
            pCard.removeAll();pCard.setVisible(false);
            lNIK.setText("-");
            lNama.setText("-");
        }
    }
    
    private void done(){
        pemilih=null;
        bilik.setIdPemilih(pemilih);
        ts.updateBilik(bilik);
        MainUi.setBilik(bilik);
        check();        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lNIK;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lTitle;
    private javax.swing.JPanel pBilik;
    private javax.swing.JPanel pCard;
    // End of variables declaration//GEN-END:variables
}
