/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.frame.dialog;

import com.twmacinta.util.MD5;
import com.voting.model.security.Admin;
import com.voting.service.SecurityService;
import com.voting.ui.frame.MainUi;
import com.voting.util.DataLogger;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Rizal
 */
public class EditPasswordDialog extends javax.swing.JDialog {
    
    private static String current, pnew;
    public static final int RET_CANCEL = 2;
    public static final int RET_OK = 0;
    Admin admin;
    SecurityService ss= MainUi.getSecurityService();

    /**
     * Creates new form CamOptionDialog
     */
    public EditPasswordDialog() {
        super(MainUi.getInstance(), true);
        initComponents();

        // <editor-fold defaultstate="collapsed" desc="Compiled Code Key Listener">
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });// </editor-fold>
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus(Admin a) {
        admin = a;current=admin.getPassword();
        System.out.println(current);
        this.setVisible(true);
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lCurrent = new javax.swing.JLabel();
        lNew = new javax.swing.JLabel();
        lRe = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        fCurrent = new javax.swing.JPasswordField();
        fNew = new javax.swing.JPasswordField();
        fRe = new javax.swing.JPasswordField();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();

        setTitle(org.openide.util.NbBundle.getMessage(EditPasswordDialog.class, "EditPasswordDialog.title")); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(360, 195));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        btnOk.setText(org.openide.util.NbBundle.getMessage(EditPasswordDialog.class, "EditPasswordDialog.btnOk.text")); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eOk(evt);
            }
        });

        btnCancel.setText(org.openide.util.NbBundle.getMessage(EditPasswordDialog.class, "EditPasswordDialog.btnCancel.text")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCancel(evt);
            }
        });

        lTitle.setFont(new java.awt.Font("Futured", 1, 24)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText(org.openide.util.NbBundle.getMessage(EditPasswordDialog.class, "EditPasswordDialog.lTitle.text")); // NOI18N

        lCurrent.setText(org.openide.util.NbBundle.getMessage(EditPasswordDialog.class, "EditPasswordDialog.lCurrent.text")); // NOI18N

        lNew.setText(org.openide.util.NbBundle.getMessage(EditPasswordDialog.class, "EditPasswordDialog.lNew.text")); // NOI18N

        lRe.setText(org.openide.util.NbBundle.getMessage(EditPasswordDialog.class, "EditPasswordDialog.lRe.text")); // NOI18N

        fCurrent.setText(org.openide.util.NbBundle.getMessage(EditPasswordDialog.class, "EditProfileDialog.fCurrent.text")); // NOI18N
        fCurrent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kCur(evt);
            }
        });

        fNew.setText(org.openide.util.NbBundle.getMessage(EditPasswordDialog.class, "EditProfileDialog.fNew.text")); // NOI18N
        fNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kNew(evt);
            }
        });

        fRe.setText(org.openide.util.NbBundle.getMessage(EditPasswordDialog.class, "EditPasswordDialog.fRe.text")); // NOI18N
        fRe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kPre(evt);
            }
        });

        l1.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText(org.openide.util.NbBundle.getMessage(EditPasswordDialog.class, "EditPasswordDialog.l1.text")); // NOI18N
        l1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        l2.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText(org.openide.util.NbBundle.getMessage(EditPasswordDialog.class, "EditPasswordDialog.l2.text")); // NOI18N
        l2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        l3.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText(org.openide.util.NbBundle.getMessage(EditPasswordDialog.class, "EditPasswordDialog.l3.text")); // NOI18N
        l3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCurrent)
                            .addComponent(lNew)
                            .addComponent(lRe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(fRe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(fCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(fNew, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnOk});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCurrent)
                    .addComponent(fCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNew)
                    .addComponent(fNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRe)
                    .addComponent(fRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOk))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(btnOk);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eOk(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eOk
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        ss.updateAdmin(admin);//ss.makeLog(DataLogger.makeLog(admin, DataLogger.PASS));
        doClose(RET_OK);// </editor-fold>
    }//GEN-LAST:event_eOk

    private void eCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCancel
        doClose(RET_CANCEL);
    }//GEN-LAST:event_eCancel

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void kCur(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kCur
        bulp(0,check(0,(new String(fCurrent.getPassword()))));
    }//GEN-LAST:event_kCur

    private void kNew(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kNew
        bulp(1,check(1,(new String(fNew.getPassword()))));
    }//GEN-LAST:event_kNew

    private void kPre(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kPre
        bulp(2,check(2,(new String(fRe.getPassword()))));
    }//GEN-LAST:event_kPre
    
    private void doClose(int retStatus) {
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        returnStatus = retStatus;
        setVisible(false);
        dispose();// </editor-fold>
    }
    
    private boolean check(int i, String s){
        String h= new MD5(s).asHex();
        switch(i){
            case 0: return current.equals(h);
            case 1: pnew=h;return !current.equals(h);
            default: admin.setPassword(h);return pnew.equals(h);
        }
    }
    
    private void bulp(int i, boolean b){
        Object[] o= {l1,l2,l3};
        javax.swing.JLabel l= (javax.swing.JLabel) o[i];
        if(b){
            l.setText("✔");l.setForeground(new java.awt.Color(0, 153, 0));
        } else{
            l.setText("✖");l.setForeground(new java.awt.Color(255, 0, 0));
        }
    }
    
    private boolean isValidated(){
        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JPasswordField fCurrent;
    private javax.swing.JPasswordField fNew;
    private javax.swing.JPasswordField fRe;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel lCurrent;
    private javax.swing.JLabel lNew;
    private javax.swing.JLabel lRe;
    private javax.swing.JLabel lTitle;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
