/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.frame.dialog;

import com.voting.model.master.Tps;
import com.voting.service.MasterService;
import com.voting.ui.frame.MainUi;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.AbstractTableModel;
/**
 *
 * @author Rizal
 */
public class GetTPS extends JDialog {
      
    private static List<Tps> tpss;
    Tps tps;
    MasterService ms = MainUi.getMasterService();

    /**
     * Creates new form LogIn
     * @param parent
     * @param modal
     */
    public GetTPS(Frame parent) {
        super(parent, true);
        initComponents();initListener();loadData();
        setLocationRelativeTo(null);
    }
    
    private void initListener() {
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        tData.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if(tData.getSelectedRow()>=0){
                int indexModel = tData.convertRowIndexToModel(tData.getSelectedRow());
                tps = tpss.get(indexModel);
            }
        });// </editor-fold>
    }
    
    private static void loadData(){
        tpss = MainUi.getMasterService().getAllTps();
        tData.setModel(new TpsModel(tpss));
    }

    private static class TpsModel extends AbstractTableModel{
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        private List<Tps> tpsModel = new ArrayList();

        public TpsModel(List<Tps> tpsModel) {
            this.tpsModel = tpsModel;
            fireTableDataChanged();
        }
        @Override
        public int getRowCount() {
            return tpsModel.size();
        }
        @Override
        public int getColumnCount() {
            return 8;
        }
        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Tps t = tpsModel.get(rowIndex);
            switch(columnIndex){
                case 0 : return t.getCode();
                case 1 : return "<HTML>"+t.getDesk().replaceAll("\n", " ")+"</HTML>";
                default : return "";
            }
        }// </editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        sType = new javax.swing.JComboBox<>();
        iForm = new javax.swing.JTextField();
        bRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin Log In");
        setResizable(false);

        lTitle.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText(org.openide.util.NbBundle.getMessage(GetTPS.class, "GetTPS.lTitle.text")); // NOI18N

        btnLogin.setText(org.openide.util.NbBundle.getMessage(GetTPS.class, "GetTPS.btnLogin.text")); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSelect(evt);
            }
        });

        btnExit.setText(org.openide.util.NbBundle.getMessage(GetTPS.class, "GetTPS.btnExit.text")); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eExit(evt);
            }
        });

        sType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Provinsi", "Kabupaten", "Kecamatan", "Desa/Kelurahan", "Kode TPS", "Deskripsi" }));
        sType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCari(evt);
            }
        });

        iForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCari(evt);
            }
        });
        iForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kCari(evt);
            }
        });

        bRefresh.setText(org.openide.util.NbBundle.getMessage(GetTPS.class, "GetTPS.bRefresh.text")); // NOI18N
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eRefresh(evt);
            }
        });

        tData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode TPS", "Deskripsi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tData);
        if (tData.getColumnModel().getColumnCount() > 0) {
            tData.getColumnModel().getColumn(0).setMinWidth(120);
            tData.getColumnModel().getColumn(0).setMaxWidth(120);
            tData.getColumnModel().getColumn(1).setResizable(false);
        }
        tData.setAutoCreateColumnsFromModel(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(iForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bRefresh)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void eExit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eExit
        dispose();
    }//GEN-LAST:event_eExit

    private void eCari(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCari
        search();
    }//GEN-LAST:event_eCari

    private void kCari(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kCari
        search();
    }//GEN-LAST:event_kCari

    private void eRefresh(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eRefresh
        refresh();
    }//GEN-LAST:event_eRefresh

    private void eSelect(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSelect
        dispose();
    }//GEN-LAST:event_eSelect
    public static void refresh(){
        iForm.setText(null);
        sType.setSelectedIndex(0);
        loadData();
    }
    public Tps getTps() {
        setVisible(true);
        return tps;
    }
    
    private void search(){
        tpss = MainUi.getMasterService().searchTps(sType.getSelectedIndex(),iForm.getText());        
        tData.setModel(new TpsModel(tpss));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private static javax.swing.JTextField iForm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lTitle;
    private static javax.swing.JComboBox<String> sType;
    private static javax.swing.JTable tData;
    // End of variables declaration//GEN-END:variables
}
