/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.security;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import javax.swing.event.ListSelectionEvent;
import javax.swing.table.AbstractTableModel;

import com.voting.model.security.Log;
import com.voting.service.SecurityService;
import com.voting.ui.frame.MainUi;

/**
 *
 * @author Rizal
 */
public class LogPanel extends javax.swing.JInternalFrame {

    private final ResourceBundle bundle = ResourceBundle.getBundle("com.voting.ui.security.Bundle");
    private final SecurityService ss = MainUi.getSecurityService();

    private static List<Log> logs;
    private Log log;

    /**
     * Creates new form LogPanel
     */
    public LogPanel() {
        initComponents();
        initListener();
        loadData();
    }

    public Log getLog() {
        return log;
    }

    public SecurityService getSecurityService() {
        return ss;
    }

    private void initListener() {
        tData.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (tData.getSelectedRow() >= 0) {
                int indexModel = tData.convertRowIndexToModel(tData.getSelectedRow());
                log = logs.get(indexModel);
                panelTombol1.Terpilih(true);
            }
        });
        panelTombol1.getBtnExit().addActionListener((ActionEvent arg0) -> {
            dispose();
        });
        panelTombol1.getBtnCancel().addActionListener((ActionEvent arg0) -> {
            panelTombol1.Terpilih(false);
        });
        panelTombol1.getBtnView().addActionListener((ActionEvent arg0) -> {
            panelTombol1.Terpilih(false);
        });
        panelTombol1.getBtnNew().setVisible(false);
        panelTombol1.getBtnEdit().setVisible(false);
        panelTombol1.getBtnDelete().setVisible(false);
    }

    private static void loadData() {
        logs = MainUi.getSecurityService().getLogs();
        tData.setModel(new LogModel(logs));
    }

    private static class LogModel extends AbstractTableModel {

        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        private List<Log> logModel = new ArrayList<>();

        public LogModel(List<Log> logModel) {
            this.logModel = logModel;
            fireTableDataChanged();
        }

        @Override
        public int getRowCount() {
            return logModel.size();
        }

        @Override
        public int getColumnCount() {
            return 3;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Log l = logModel.get(rowIndex);
            return switch (columnIndex) {
                case 0 ->
                    l.getTime();
                case 1 ->
                    l.getAdminId();
                case 2 ->
                    l.getDescription();
                default ->
                    "";
            };
        }// </editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sType = new javax.swing.JComboBox<>();
        iForm = new javax.swing.JTextField();
        bRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tData = new javax.swing.JTable();
        panelTombol1 = new com.voting.ui.panel.PanelTombol();

        setTitle(bundle.getString("LogPanel.title")); // NOI18N

        lTitle.setFont(new java.awt.Font("Futured", 1, 24)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText(bundle.getString("LogPanel.lTitle.text")); // NOI18N

        sType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Waktu", "Admin Username"}));

        iForm.setText(bundle.getString("LogPanel.iForm.text")); // NOI18N

        bRefresh.setText(bundle.getString("LogPanel.bRefresh.text")); // NOI18N
        bRefresh.addActionListener(e -> loadData());

        tData.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Waktu", "Username", "Deskripsi"
                }
        ));
        jScrollPane1.setViewportView(tData);
        if (tData.getColumnModel().getColumnCount() > 0) {
            tData.getColumnModel().getColumn(0).setMinWidth(150);
            tData.getColumnModel().getColumn(0).setMaxWidth(150);
            tData.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("LogPanel.tData.columnModel.title0")); // NOI18N
            tData.getColumnModel().getColumn(1).setMinWidth(150);
            tData.getColumnModel().getColumn(1).setMaxWidth(150);
            tData.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("LogPanel.tData.columnModel.title1")); // NOI18N
            tData.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("LogPanel.tData.columnModel.title2")); // NOI18N
        }
        tData.setAutoCreateColumnsFromModel(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(sType, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(iForm)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bRefresh))
                                        .addComponent(panelTombol1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(iForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bRefresh))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelTombol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRefresh;
    private javax.swing.JTextField iForm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lTitle;
    private com.voting.ui.panel.PanelTombol panelTombol1;
    private javax.swing.JComboBox<String> sType;
    private static javax.swing.JTable tData;
    // End of variables declaration//GEN-END:variables
}
