/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.security;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.AbstractTableModel;

import com.voting.model.security.Admin;
import com.voting.service.SecurityService;
import com.voting.ui.frame.MainUi;
import com.voting.ui.security.dialog.InputPetugas;
import com.voting.ui.security.dialog.ViewPetugas;
import com.voting.util.UploadImg;

/**
 *
 * @author Rizal
 */
public class PetugasPanel extends javax.swing.JInternalFrame {

    private final ResourceBundle bundle = ResourceBundle.getBundle("com.voting.ui.security.Bundle");

    private static List<Admin> admins;
    private Admin admin;
    SecurityService ss = MainUi.getSecurityService();

    /**
     * Creates new form PetugasPanel
     */
    public PetugasPanel() {
        initComponents();
        initListener();
        loadData();
    }

    private void initListener() {
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        tData.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (tData.getSelectedRow() >= 0) {
                int indexModel = tData.convertRowIndexToModel(tData.getSelectedRow());
                admin = admins.get(indexModel);
                panelTombol1.Terpilih(true);
            }
        });
        panelTombol1.getBtnExit().addActionListener((ActionEvent e) -> {
            dispose();
        });
        panelTombol1.getBtnNew().addActionListener((ActionEvent e) -> {
            InputPetugas ad = new InputPetugas();
            ad.setVisible(true);
            panelTombol1.Disable();
        });
        panelTombol1.getBtnView().addActionListener((ActionEvent e) -> {
            ViewPetugas view = new ViewPetugas();
            panelTombol1.Disable();
            int data = view.setData(admin);
            if (data == 0) {
                panelTombol1.Terpilih(true);
            }
        });
        panelTombol1.getBtnEdit().addActionListener((ActionEvent e) -> {
            InputPetugas ad = new InputPetugas(admin, 0);
            ad.setVisible(true);
            panelTombol1.Disable();
        });
        panelTombol1.getBtnDelete().addActionListener((ActionEvent e) -> {
            panelTombol1.Disable();
            int Pilih = JOptionPane.showConfirmDialog(this, "Apakah anda yakin akan menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (Pilih == JOptionPane.YES_OPTION) {
                ss.deleteAdmin(admin);
                UploadImg.deletePhoto(admin.getFoto());
                refresh();
                JOptionPane.showMessageDialog(this, "PENGHAPUSAN BERHASIL");
            } else {
                panelTombol1.Terpilih(true);
            }
        });
        panelTombol1.getBtnCancel().addActionListener((ActionEvent e) -> {
            tData.clearSelection();
            admin = null;
            panelTombol1.Terpilih(false);
        });// </editor-fold>
    }

    private static void loadData() {
        admins = MainUi.getSecurityService().getAdmins();
        tData.setModel(new AdminModel(admins));
    }

    private static class AdminModel extends AbstractTableModel {

        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        private List<Admin> adminModel = new ArrayList<>();

        public AdminModel(List<Admin> adminModel) {
            this.adminModel = adminModel;
            fireTableDataChanged();
        }

        @Override
        public int getRowCount() {
            return adminModel.size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Admin a = adminModel.get(rowIndex);
            //String t="";for(Acc ac:a.getAccList()){t=ac.getId();}
            return switch (columnIndex) {
                case 0 ->
                    a.getUsername();
                case 1 ->
                    a.getNama();
                case 2 ->
                    a.getAcc();
                case 3 ->
                    a.getTpsCode();
                default ->
                    "";
            };
        }// </editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sType = new javax.swing.JComboBox<>();
        bRefresh = new javax.swing.JButton();
        iForm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tData = new javax.swing.JTable();
        panelTombol1 = new com.voting.ui.panel.PanelTombol();

        setTitle(bundle.getString("PetugasPanel.title")); // NOI18N

        lTitle.setFont(new java.awt.Font("Futured", 1, 24)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText(bundle.getString("PetugasPanel.lTitle.text")); // NOI18N

        sType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Username", "Nama", "Tugas", "Kode TPS"}));
        sType.addActionListener(e -> search());

        bRefresh.setText(bundle.getString("PetugasPanel.bRefresh.text")); // NOI18N
        bRefresh.addActionListener(e -> refresh());

        iForm.addActionListener(e -> search());
        iForm.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search();
            }
        });

        tData.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Username", "Nama Lengkap", "Tugas", "Kode TPS"
                }
        ));
        jScrollPane1.setViewportView(tData);
        if (tData.getColumnModel().getColumnCount() > 0) {
            tData.getColumnModel().getColumn(0).setMinWidth(100);
            tData.getColumnModel().getColumn(0).setMaxWidth(150);
            tData.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("PetugasPanel.tData.columnModel.title0")); // NOI18N
            tData.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("PetugasPanel.tData.columnModel.title1")); // NOI18N
            tData.getColumnModel().getColumn(2).setMinWidth(150);
            tData.getColumnModel().getColumn(2).setMaxWidth(150);
            tData.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("PetugasPanel.tData.columnModel.title2")); // NOI18N
            tData.getColumnModel().getColumn(3).setMinWidth(120);
            tData.getColumnModel().getColumn(3).setMaxWidth(120);
            tData.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("PetugasPanel.tData.columnModel.title3")); // NOI18N
        }
        tData.setAutoCreateColumnsFromModel(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator1)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(sType, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(iForm)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bRefresh))
                                        .addComponent(panelTombol1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bRefresh)
                                        .addComponent(iForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelTombol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void refresh() {
        panelTombol1.Terpilih(false);
        iForm.setText(null);
        sType.setSelectedIndex(0);
        loadData();
    }

    private void search() {
        //admins = ss.searchCalon(sType.getSelectedIndex(),iForm.getText());        
        //tData.setModel(new AdminModel(admins));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton bRefresh;
    private static javax.swing.JTextField iForm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lTitle;
    private static com.voting.ui.panel.PanelTombol panelTombol1;
    private static javax.swing.JComboBox<String> sType;
    private static javax.swing.JTable tData;
    // End of variables declaration//GEN-END:variables
}
