/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.master.dialog;

import com.voting.model.master.Tps;
import com.voting.model.master.tps.*;
import com.voting.service.MasterService;
import com.voting.service.SecurityService;
import com.voting.ui.frame.MainUi;
import com.voting.ui.master.TpsPanel;
import com.voting.util.DataLogger;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rizal
 */
public class InputTps extends javax.swing.JFrame {
    Tps tps;String no;
    MasterService ms = MainUi.getMasterService();
    SecurityService ss = MainUi.getSecurityService();

    /**
     * Creates new form InputTps
     */
    public InputTps() {
        initComponents();
    }
    
    public InputTps(Tps t){
        initComponents();
        tps=t;loadTps(tps);
        tpsIsSet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pTps = new javax.swing.JPanel();
        lProv = new javax.swing.JLabel();
        lKab = new javax.swing.JLabel();
        lKec = new javax.swing.JLabel();
        lDes = new javax.swing.JLabel();
        lNo = new javax.swing.JLabel();
        lKode = new javax.swing.JLabel();
        cProv = new javax.swing.JComboBox<>();
        cKab = new javax.swing.JComboBox<>();
        cKec = new javax.swing.JComboBox<>();
        cDes = new javax.swing.JComboBox<>();
        fNo = new javax.swing.JTextField();
        fCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fDesk = new javax.swing.JTextArea();
        bSave = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(InputTps.class, "InputTps.title")); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                wExit(evt);
            }
        });

        lTitle.setFont(new java.awt.Font("Futured", 1, 24)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText(org.openide.util.NbBundle.getMessage(InputTps.class, "InputTps.lTitle.text")); // NOI18N

        pTps.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(InputTps.class, "InputTps.pTps.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Futured", 1, 12))); // NOI18N

        lProv.setText(org.openide.util.NbBundle.getMessage(InputTps.class, "InputTps.lProv.text")); // NOI18N

        lKab.setText(org.openide.util.NbBundle.getMessage(InputTps.class, "InputTps.lKab.text")); // NOI18N

        lKec.setText(org.openide.util.NbBundle.getMessage(InputTps.class, "InputTps.lKec.text")); // NOI18N

        lDes.setText(org.openide.util.NbBundle.getMessage(InputTps.class, "InputTps.lDes.text")); // NOI18N

        lNo.setText(org.openide.util.NbBundle.getMessage(InputTps.class, "InputTps.lNo.text")); // NOI18N

        lKode.setText(org.openide.util.NbBundle.getMessage(InputTps.class, "InputTps.lKode.text")); // NOI18N

        List<Prov> prov = ms.getAllProv();
        cProv.setModel(new DefaultComboBoxModel<Prov>(prov.toArray(new Prov[0])));
        cProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oKab(evt);
            }
        });

        cKab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oKec(evt);
            }
        });

        cKec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oDes(evt);
            }
        });

        cDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oCode(evt);
            }
        });

        fNo.setText(org.openide.util.NbBundle.getMessage(InputTps.class, "InputTps.fNo.text")); // NOI18N
        fNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kCode(evt);
            }
        });

        fCode.setEditable(false);
        fCode.setText(org.openide.util.NbBundle.getMessage(InputTps.class, "InputTps.fCode.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(InputTps.class, "InputTps.jLabel1.text")); // NOI18N

        fDesk.setColumns(20);
        fDesk.setRows(3);
        jScrollPane1.setViewportView(fDesk);

        javax.swing.GroupLayout pTpsLayout = new javax.swing.GroupLayout(pTps);
        pTps.setLayout(pTpsLayout);
        pTpsLayout.setHorizontalGroup(
            pTpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTpsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lProv)
                    .addComponent(lKab)
                    .addComponent(lKec)
                    .addComponent(lDes))
                .addGap(51, 51, 51)
                .addGroup(pTpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cKec, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cKab, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pTpsLayout.createSequentialGroup()
                        .addComponent(cProv, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(pTpsLayout.createSequentialGroup()
                        .addComponent(cDes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lNo)))
                .addGap(18, 18, 18)
                .addGroup(pTpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTpsLayout.createSequentialGroup()
                        .addComponent(fNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lKode)
                        .addGap(18, 18, 18)
                        .addComponent(fCode))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                .addContainerGap())
        );
        pTpsLayout.setVerticalGroup(
            pTpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTpsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pTpsLayout.createSequentialGroup()
                        .addGroup(pTpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lProv)
                            .addComponent(cProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pTpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lKab)
                            .addComponent(cKab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pTpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lKec)
                            .addComponent(cKec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pTpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDes)
                    .addComponent(cDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNo)
                    .addComponent(fNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lKode)
                    .addComponent(fCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bSave.setText(org.openide.util.NbBundle.getMessage(InputTps.class, "InputTps.bSave.text")); // NOI18N
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSave(evt);
            }
        });

        bCancel.setText(org.openide.util.NbBundle.getMessage(InputTps.class, "InputTps.bCancel.text")); // NOI18N
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eExit(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pTps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pTps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSave)
                    .addComponent(bCancel))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void oKab(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oKab
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        cKab.setEnabled(true);cKec.setEnabled(false);cDes.setEnabled(false);
        List<Kab> kab = ms.getFromProv((Prov)cProv.getSelectedItem());
        cKab.setModel(new DefaultComboBoxModel<Kab>(kab.toArray(new Kab[0])));
        fCode.setText(setCode(cProv.getSelectedItem()));//</editor-fold>
    }//GEN-LAST:event_oKab

    private void oKec(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oKec
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        cKec.setEnabled(true);cDes.setEnabled(false);
        List<Kec> kec = ms.getFromKab((Kab)cKab.getSelectedItem());
        cKec.setModel(new DefaultComboBoxModel<Kec>(kec.toArray(new Kec[0])));
        fCode.setText(setCode(cKab.getSelectedItem()));//</editor-fold>
    }//GEN-LAST:event_oKec

    private void oDes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oDes
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        cDes.setEnabled(true);
        List<Des> des = ms.getFromKec((Kec)cKec.getSelectedItem());
        cDes.setModel(new DefaultComboBoxModel<Des>(des.toArray(new Des[0])));
        fCode.setText(setCode(cKec.getSelectedItem()));//</editor-fold>
    }//GEN-LAST:event_oDes

    private void kCode(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kCode
        if(fNo.getText().length()<=2){
            no=fNo.getText();
            fCode.setText(setTpsCode((Des)cDes.getSelectedItem(),no));
        } else{
            JOptionPane.showMessageDialog(this,
                "Nomor TPS Tidak Boleh Lebih dari 99", "Melebihi Jumlah Maksimum", JOptionPane.ERROR_MESSAGE);
            fNo.setText(no);fNo.requestFocus();
        }
    }//GEN-LAST:event_kCode

    private void eSave(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSave
        if(isValidated()){           
            if(tps==null){
                if(ms.getTps(fCode.getText())!=null){
                    JOptionPane.showMessageDialog(this,
                            "TPS Sudah Terdaftar", "Data Sudah Ada", JOptionPane.ERROR_MESSAGE);                    
                } else{
                    ms.saveTps(setTps());
                    ss.makeLog(DataLogger.makeLog(setTps(), DataLogger.ADD));
                    dispose();
                }
            } else{
                ms.updateTPS(setTps());
                ss.makeLog(DataLogger.makeLog(setTps(), DataLogger.EDIT));
                dispose();
            }
        }
    }//GEN-LAST:event_eSave

    private void eExit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eExit
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        dispose();
        // </editor-fold>
    }//GEN-LAST:event_eExit

    private void wExit(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_wExit
        TpsPanel.refresh();
    }//GEN-LAST:event_wExit

    private void oCode(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oCode
        fCode.setText(setCode(cDes.getSelectedItem()));
    }//GEN-LAST:event_oCode

    private void loadTps(Tps t){
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        cKab.setEnabled(true);cKec.setEnabled(true);cDes.setEnabled(true);
        List<Kab> kab = ms.getFromProv(t.getProvCode());
        List<Kec> kec = ms.getFromKab(t.getKabCode());
        List<Des> des = ms.getFromKec(t.getKecCode());
        cKab.setModel(new DefaultComboBoxModel<Kab>(kab.toArray(new Kab[0])));
        cKec.setModel(new DefaultComboBoxModel<Kec>(kec.toArray(new Kec[0])));
        cDes.setModel(new DefaultComboBoxModel<Des>(des.toArray(new Des[0])));
        cProv.setSelectedItem(t.getProvCode());cKab.setSelectedItem(t.getKabCode());
        cKec.setSelectedItem(t.getKecCode());cDes.setSelectedItem(t.getDesCode());
        fDesk.setText(t.getDesk());fNo.setText(t.getNo());fCode.setText(t.getCode());//</editor-fold>
    }
    private void tpsIsSet(){
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        Object[] o= {cProv,cKab,cKec,cDes,fNo};
        for(Object t : o){
            if(t instanceof javax.swing.JComboBox){
                ((javax.swing.JComboBox) t).setEnabled(false);
            } else{
                ((javax.swing.JTextField) t).setEditable(false);
            }
        }// </editor-fold>
    }
    private String setCode(Object o){
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        if(o instanceof Prov){
            return ((Prov) o).getCode();
        } else if(o instanceof Kab){
            return ((Kab) o).getCode();
        } else if(o instanceof Kec){
            return ((Kec) o).getCode();
        } else{
            return ((Des) o).getCode(); 
        }//</editor-fold>
    }
    private String setTpsCode(Des d, String no){
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        if(no.length()==1){no=".0"+no;}else{no="."+no;}
        return d.getCode()+no+"";//</editor-fold>
    }
    private Tps setTps(){
        // <editor-fold defaultstate="collapsed" desc="Compiled Code">
        if(tps==null){
            Prov p=(Prov)cProv.getSelectedItem();Kab b=(Kab)cKab.getSelectedItem();
            Kec c=(Kec)cKec.getSelectedItem();Des d=(Des)cDes.getSelectedItem();
            String code=fCode.getText(), noo=fNo.getText(), desk=fDesk.getText();
            
            tps=new Tps(p,b,c,d,code,noo,desk);
        } else{
            tps.setDesk(fDesk.getText());
        }
        return tps;//</editor-fold>
    }
    private boolean isValidated(){
        if(fCode.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,
                "TPS Belum Diatur","TPS Harus Diisi", JOptionPane.ERROR_MESSAGE);
            fNo.requestFocus();
            return false;
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bSave;
    private javax.swing.JComboBox<Des> cDes;
    private javax.swing.JComboBox<Kab> cKab;
    private javax.swing.JComboBox<Kec> cKec;
    private javax.swing.JComboBox<Prov> cProv;
    private javax.swing.JTextField fCode;
    private javax.swing.JTextArea fDesk;
    private javax.swing.JTextField fNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lDes;
    private javax.swing.JLabel lKab;
    private javax.swing.JLabel lKec;
    private javax.swing.JLabel lKode;
    private javax.swing.JLabel lNo;
    private javax.swing.JLabel lProv;
    private static javax.swing.JLabel lTitle;
    private javax.swing.JPanel pTps;
    // End of variables declaration//GEN-END:variables
}
