/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.master.dialog;

import com.voting.model.master.Tps;
import com.voting.ui.frame.MainUi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Rizal
 */
public class ViewTps extends javax.swing.JDialog implements ActionListener{
    public static final int RET_NORMAL = 1;
    public static final int RET_CLOSE = 0;


    @Override
    public void actionPerformed(ActionEvent ae) {
        doClose(RET_CLOSE);
    }
    /**
     * Creates new form ViewPemilih
     * @param p
     */
    public ViewTps() {
        super(MainUi.getInstance(), true);
        initComponents();
    }
    
    public int setData(Tps t, long l){
        loadData(t,l);
        this.setVisible(true);
        return stat;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        panelProfil = new javax.swing.JPanel();
        lProv = new javax.swing.JLabel();
        lKab = new javax.swing.JLabel();
        lKec = new javax.swing.JLabel();
        lDes = new javax.swing.JLabel();
        lDesk = new javax.swing.JLabel();
        lNo = new javax.swing.JLabel();
        lCode = new javax.swing.JLabel();
        lJum = new javax.swing.JLabel();
        k1 = new javax.swing.JLabel();
        k2 = new javax.swing.JLabel();
        k3 = new javax.swing.JLabel();
        k4 = new javax.swing.JLabel();
        k5 = new javax.swing.JLabel();
        k6 = new javax.swing.JLabel();
        k7 = new javax.swing.JLabel();
        k8 = new javax.swing.JLabel();
        fProv = new javax.swing.JLabel();
        fKab = new javax.swing.JLabel();
        fKec = new javax.swing.JLabel();
        fDes = new javax.swing.JLabel();
        fDesk = new javax.swing.JLabel();
        fNo = new javax.swing.JLabel();
        fCode = new javax.swing.JLabel();
        fJum = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.title")); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                wClose(evt);
            }
        });

        lTitle.setFont(new java.awt.Font("Futured", 1, 24)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.lTitle.text")); // NOI18N

        panelProfil.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.panelProfil.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Futured", 1, 12))); // NOI18N

        lProv.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.lProv.text")); // NOI18N

        lKab.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.lKab.text")); // NOI18N

        lKec.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.lKec.text")); // NOI18N

        lDes.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.lDes.text")); // NOI18N

        lDesk.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.lDesk.text")); // NOI18N

        lNo.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.lNo.text")); // NOI18N

        lCode.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.lCode.text")); // NOI18N

        lJum.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.lJum.text")); // NOI18N

        k1.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.k1.text")); // NOI18N

        k2.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.k2.text")); // NOI18N

        k3.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.k3.text")); // NOI18N

        k4.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.k4.text")); // NOI18N

        k5.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.k5.text")); // NOI18N

        k6.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.k6.text")); // NOI18N

        k7.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.k7.text")); // NOI18N

        k8.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.k8.text")); // NOI18N

        fProv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fProv.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.fProv.text")); // NOI18N

        fKab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fKab.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.fKab.text")); // NOI18N

        fKec.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fKec.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.fKec.text")); // NOI18N

        fDes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fDes.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.fDes.text")); // NOI18N

        fDesk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fDesk.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.fDesk.text")); // NOI18N

        fNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fNo.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.fNo.text")); // NOI18N

        fCode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fCode.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.fCode.text")); // NOI18N

        fJum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fJum.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.fJum.text")); // NOI18N

        javax.swing.GroupLayout panelProfilLayout = new javax.swing.GroupLayout(panelProfil);
        panelProfil.setLayout(panelProfilLayout);
        panelProfilLayout.setHorizontalGroup(
            panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lKec)
                    .addComponent(lKab)
                    .addComponent(lProv)
                    .addComponent(lDes)
                    .addComponent(lNo)
                    .addComponent(lCode)
                    .addComponent(lJum)
                    .addComponent(lDesk))
                .addGap(41, 41, 41)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProfilLayout.createSequentialGroup()
                        .addComponent(k8, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fDesk, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelProfilLayout.createSequentialGroup()
                        .addComponent(k6, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fDes, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fNo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fCode, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelProfilLayout.createSequentialGroup()
                        .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(k5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(k4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(k3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fKec, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelProfilLayout.createSequentialGroup()
                        .addComponent(k7, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fJum, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelProfilLayout.createSequentialGroup()
                        .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(k2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(k1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fProv, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fKab, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProfilLayout.setVerticalGroup(
            panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lProv)
                    .addComponent(k1)
                    .addComponent(fProv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lKab)
                    .addComponent(k2)
                    .addComponent(fKab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lKec)
                    .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(k3)
                        .addComponent(fKec)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDes)
                    .addComponent(k4)
                    .addComponent(fDes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDesk)
                    .addComponent(k8)
                    .addComponent(fDesk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNo)
                    .addComponent(k5)
                    .addComponent(fNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCode)
                    .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(k6)
                        .addComponent(fCode)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lJum)
                    .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(k7)
                        .addComponent(fJum)))
                .addContainerGap())
        );

        btnClose.setText(org.openide.util.NbBundle.getMessage(ViewTps.class, "ViewTps.btnClose.text")); // NOI18N
        btnClose.addActionListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void wClose(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_wClose
        doClose(RET_CLOSE);
    }//GEN-LAST:event_wClose
    
    private void loadData(Tps t, long l){
        if(stat == RET_NORMAL){
            fProv.setText(t.getProvCode().toString());
            fKab.setText(t.getKabCode().toString());
            fKec.setText(t.getKecCode().toString());
            fDes.setText(t.getDesCode().toString());
            fDesk.setText("<HTML>"+t.getDesk().replaceAll("\n", " ")+"</HTML>");
            fNo.setText(t.getNo());fCode.setText(t.toString());fJum.setText(""+l);
        }        
    }
    
    private void doClose(int retStatus) {
        stat = retStatus;
        setVisible(false);
        dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel fCode;
    private javax.swing.JLabel fDes;
    private javax.swing.JLabel fDesk;
    private javax.swing.JLabel fJum;
    private javax.swing.JLabel fKab;
    private javax.swing.JLabel fKec;
    private javax.swing.JLabel fNo;
    private javax.swing.JLabel fProv;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel k1;
    private javax.swing.JLabel k2;
    private javax.swing.JLabel k3;
    private javax.swing.JLabel k4;
    private javax.swing.JLabel k5;
    private javax.swing.JLabel k6;
    private javax.swing.JLabel k7;
    private javax.swing.JLabel k8;
    private javax.swing.JLabel lCode;
    private javax.swing.JLabel lDes;
    private javax.swing.JLabel lDesk;
    private javax.swing.JLabel lJum;
    private javax.swing.JLabel lKab;
    private javax.swing.JLabel lKec;
    private javax.swing.JLabel lNo;
    private javax.swing.JLabel lProv;
    private javax.swing.JLabel lTitle;
    private javax.swing.JPanel panelProfil;
    // End of variables declaration//GEN-END:variables
    
    private int stat = RET_NORMAL;
}
