/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.security.dialog;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

import org.openide.util.Exceptions;

import com.twmacinta.util.MD5;
import com.voting.model.master.Tps;
import com.voting.model.security.Admin;
import com.voting.service.SecurityService;
import com.voting.ui.frame.MainUi;
import com.voting.util.DataLogger;

/**
 *
 * @author Rizal
 */
public class ViewPetugas extends javax.swing.JDialog implements ActionListener {

    private final ResourceBundle bundle = ResourceBundle.getBundle("com.voting.ui.security.dialog.Bundle");
    BufferedImage foto;
    Admin admin;
    public static final int RET_NORMAL = 1;
    public static final int RET_CLOSE = 0;
    SecurityService ss = MainUi.getSecurityService();

    @Override
    public void actionPerformed(ActionEvent ae) {
        doClose(RET_CLOSE);
    }

    /**
     * Creates new form ViewPemilih
     *
     * @param p
     */
    public ViewPetugas() {
        super(MainUi.getInstance(), true);
        initComponents();
    }

    public int setData(Admin a) {
        admin = a;
        loadData(admin);
        this.setVisible(true);
        return stat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        panelProfil = new javax.swing.JPanel();
        panelFoto = new com.voting.ui.panel.PanelFoto();
        lNama = new javax.swing.JLabel();
        lUname = new javax.swing.JLabel();
        lRole = new javax.swing.JLabel();
        lTps = new javax.swing.JLabel();
        k1 = new javax.swing.JLabel();
        k2 = new javax.swing.JLabel();
        k3 = new javax.swing.JLabel();
        k4 = new javax.swing.JLabel();
        fNama = new javax.swing.JLabel();
        fUname = new javax.swing.JLabel();
        fRole = new javax.swing.JLabel();
        fTps = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(bundle.getString("ViewPetugas.title")); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                doClose(RET_CLOSE);
            }
        });

        lTitle.setFont(new java.awt.Font("Futured", 1, 24)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText(bundle.getString("ViewPetugas.lTitle.text")); // NOI18N

        panelProfil.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("ViewPetugas.panelProfil.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Futured", 1, 12))); // NOI18N

        panelFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout panelFotoLayout = new javax.swing.GroupLayout(panelFoto);
        panelFoto.setLayout(panelFotoLayout);
        panelFotoLayout.setHorizontalGroup(
                panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 87, Short.MAX_VALUE)
        );
        panelFotoLayout.setVerticalGroup(
                panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 108, Short.MAX_VALUE)
        );

        lNama.setText(bundle.getString("ViewPetugas.lNama.text")); // NOI18N

        lUname.setText(bundle.getString("ViewPetugas.lUname.text")); // NOI18N

        lRole.setText(bundle.getString("ViewPetugas.lRole.text")); // NOI18N

        lTps.setText(bundle.getString("ViewPetugas.lTps.text")); // NOI18N

        k1.setText(bundle.getString("ViewPetugas.k1.text")); // NOI18N

        k2.setText(bundle.getString("ViewPetugas.k2.text")); // NOI18N

        k3.setText(bundle.getString("ViewPetugas.k3.text")); // NOI18N

        k4.setText(bundle.getString("ViewPetugas.k4.text")); // NOI18N

        fNama.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fNama.setText(bundle.getString("ViewPetugas.fNama.text")); // NOI18N

        fUname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fUname.setText(bundle.getString("ViewPetugas.fUname.text")); // NOI18N

        fRole.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fRole.setText(bundle.getString("ViewPetugas.fRole.text")); // NOI18N

        fTps.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fTps.setText(bundle.getString("ViewPetugas.fTps.text")); // NOI18N

        javax.swing.GroupLayout panelProfilLayout = new javax.swing.GroupLayout(panelProfil);
        panelProfil.setLayout(panelProfilLayout);
        panelProfilLayout.setHorizontalGroup(
                panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelProfilLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lRole)
                                        .addComponent(lUname)
                                        .addComponent(lNama)
                                        .addComponent(lTps))
                                .addGap(41, 41, 41)
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelProfilLayout.createSequentialGroup()
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(k2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(k1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(fNama, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fUname, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(panelProfilLayout.createSequentialGroup()
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(k4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(k3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(fRole, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fTps, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(panelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addContainerGap())
        );
        panelProfilLayout.setVerticalGroup(
                panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelProfilLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(panelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                        .addGroup(panelProfilLayout.createSequentialGroup()
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lNama)
                                                        .addComponent(k1)
                                                        .addComponent(fNama))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lUname)
                                                        .addComponent(k2)
                                                        .addComponent(fUname))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lRole)
                                                        .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(k3)
                                                                .addComponent(fRole)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lTps)
                                                        .addComponent(k4)
                                                        .addComponent(fTps))))
                                .addContainerGap())
        );

        btnClose.setText(bundle.getString("ViewPetugas.btnClose.text")); // NOI18N
        btnClose.addActionListener(this);

        btnReset.setText(bundle.getString("ViewPetugas.btnReset.text")); // NOI18N
        btnReset.addActionListener(e -> eReset());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnReset)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnClose)))
                                .addContainerGap())
                        .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnClose)
                                        .addComponent(btnReset))
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eReset() {//GEN-FIRST:event_eReset
        int Pilih = JOptionPane.showConfirmDialog(this, "Apakah anda yakin akan mereset password data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (Pilih == JOptionPane.YES_OPTION) {
            resetPass(admin.getUsername());
            ss.makeLog(DataLogger.makeLog(admin, DataLogger.RST));
            JOptionPane.showMessageDialog(this, "RESET PASSWORD BERHASIL");
        }
    }//GEN-LAST:event_eReset

    private void loadData(Admin a) {
        if (stat == RET_NORMAL) {
            fNama.setText(a.getNama());
            fUname.setText(a.getUsername());
            fRole.setText(a.getAcc().getId());
            setTps(a.getTpsCode());
            setFoto(a.getFoto());
            lTitle.setText("Data " + a.getNama());
        }
    }

    private boolean setFoto(String u) {
        if (u == null) {
            panelFoto.setImage(null);
            return false;
        }
        u = u.replace("address", MainUi.getAppsIp());
        try {
            URL url = new URL(u);
            foto = ImageIO.read(url);
            panelFoto.setImage(foto);
            return true;
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
        return false;
    }

    private void setTps(Tps t) {
        if (t != null) {
            fTps.setText(t.getCode());
        } else {
            fTps.setText("-");
        }
    }

    private boolean resetPass(String p) {
        String pass = new MD5(p).asHex();
        admin.setPassword(pass);
        ss.updateAdmin(admin);
        return true;
    }

    private void doClose(int retStatus) {
        stat = retStatus;
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel fNama;
    private javax.swing.JLabel fRole;
    private javax.swing.JLabel fTps;
    private javax.swing.JLabel fUname;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel k1;
    private javax.swing.JLabel k2;
    private javax.swing.JLabel k3;
    private javax.swing.JLabel k4;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lRole;
    private javax.swing.JLabel lTitle;
    private javax.swing.JLabel lTps;
    private javax.swing.JLabel lUname;
    private com.voting.ui.panel.PanelFoto panelFoto;
    private javax.swing.JPanel panelProfil;
    // End of variables declaration//GEN-END:variables

    private int stat = RET_NORMAL;
}
