/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.master.dialog;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.net.URL;
import java.util.EnumMap;
import java.util.Map;
import java.util.ResourceBundle;

import javax.imageio.ImageIO;

import org.openide.util.Exceptions;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import com.twmacinta.util.MD5;
import com.voting.model.master.Pemilih;
import com.voting.model.master.Tps;
import com.voting.ui.frame.MainUi;
import com.voting.util.PrintUtils;
import com.voting.util.StringUtils;

/**
 *
 * @author Rizal
 */
public class ViewPemilih extends javax.swing.JDialog implements ActionListener {

    private final ResourceBundle bundle = ResourceBundle.getBundle("com.voting.ui.master.dialog.Bundle");
    BufferedImage foto, qr;
    Pemilih pemilih;
    int urut;
    public static final int RET_NORMAL = 1;
    public static final int RET_CLOSE = 0;

    @Override
    public void actionPerformed(ActionEvent ae) {
        doClose(RET_CLOSE);
    }

    /**
     * Creates new form ViewPemilih
     *
     * @param p
     */
    public ViewPemilih() {
        super(MainUi.getInstance(), true);
        initComponents();
    }

    public int setData(Pemilih p, int i) {
        pemilih = p;
        loadData(pemilih);
        urut = i;
        this.setVisible(true);
        return stat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        panelProfil = new javax.swing.JPanel();
        panelFoto = new com.voting.ui.panel.PanelFoto();
        panelQR = new com.voting.ui.panel.PanelFoto();
        lInduk = new javax.swing.JLabel();
        lKK = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();
        lTTL = new javax.swing.JLabel();
        lStatus = new javax.swing.JLabel();
        lUmur = new javax.swing.JLabel();
        lJk = new javax.swing.JLabel();
        lAlamat = new javax.swing.JLabel();
        lDukuh = new javax.swing.JLabel();
        lRT = new javax.swing.JLabel();
        lRW = new javax.swing.JLabel();
        lDifabel = new javax.swing.JLabel();
        k1 = new javax.swing.JLabel();
        k2 = new javax.swing.JLabel();
        k3 = new javax.swing.JLabel();
        k4 = new javax.swing.JLabel();
        k5 = new javax.swing.JLabel();
        k6 = new javax.swing.JLabel();
        k7 = new javax.swing.JLabel();
        k8 = new javax.swing.JLabel();
        k9 = new javax.swing.JLabel();
        k10 = new javax.swing.JLabel();
        k11 = new javax.swing.JLabel();
        fKK = new javax.swing.JLabel();
        fNIK = new javax.swing.JLabel();
        fNama = new javax.swing.JLabel();
        fTTL = new javax.swing.JLabel();
        fStat = new javax.swing.JLabel();
        fRw = new javax.swing.JLabel();
        fJK = new javax.swing.JLabel();
        fDukuh = new javax.swing.JLabel();
        fRt = new javax.swing.JLabel();
        fUmur = new javax.swing.JLabel();
        fDifabel = new javax.swing.JLabel();
        panelTPS = new javax.swing.JPanel();
        lProv = new javax.swing.JLabel();
        fProv = new javax.swing.JLabel();
        lKab = new javax.swing.JLabel();
        fKab = new javax.swing.JLabel();
        lKec = new javax.swing.JLabel();
        fKec = new javax.swing.JLabel();
        lDes = new javax.swing.JLabel();
        fDes = new javax.swing.JLabel();
        lNo = new javax.swing.JLabel();
        fNo = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(bundle.getString("ViewPemilih.title")); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                doClose(RET_CLOSE);
            }
        });

        lTitle.setFont(new java.awt.Font("Futured", 1, 24)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText(bundle.getString("ViewPemilih.lTitle.text")); // NOI18N

        panelProfil.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("ViewPemilih.panelProfil.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Futured", 1, 12))); // NOI18N

        panelFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout panelFotoLayout = new javax.swing.GroupLayout(panelFoto);
        panelFoto.setLayout(panelFotoLayout);
        panelFotoLayout.setHorizontalGroup(
                panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 103, Short.MAX_VALUE)
        );
        panelFotoLayout.setVerticalGroup(
                panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        panelQR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout panelQRLayout = new javax.swing.GroupLayout(panelQR);
        panelQR.setLayout(panelQRLayout);
        panelQRLayout.setHorizontalGroup(
                panelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 54, Short.MAX_VALUE)
        );
        panelQRLayout.setVerticalGroup(
                panelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 54, Short.MAX_VALUE)
        );

        lInduk.setText(bundle.getString("ViewPemilih.lInduk.text")); // NOI18N

        lKK.setText(bundle.getString("ViewPemilih.lKK.text")); // NOI18N

        lNama.setText(bundle.getString("ViewPemilih.lNama.text")); // NOI18N

        lTTL.setText(bundle.getString("ViewPemilih.lTTL.text")); // NOI18N

        lStatus.setText(bundle.getString("ViewPemilih.lStatus.text")); // NOI18N

        lUmur.setText(bundle.getString("ViewPemilih.lUmur.text")); // NOI18N

        lJk.setText(bundle.getString("ViewPemilih.lJk.text")); // NOI18N

        lAlamat.setText(bundle.getString("ViewPemilih.lAlamat.text")); // NOI18N

        lDukuh.setText(bundle.getString("ViewPemilih.lDukuh.text")); // NOI18N

        lRT.setText(bundle.getString("ViewPemilih.lRT.text")); // NOI18N

        lRW.setText(bundle.getString("ViewPemilih.lRW.text")); // NOI18N

        lDifabel.setText(bundle.getString("ViewPemilih.lDifabel.text")); // NOI18N

        k1.setText(bundle.getString("ViewPemilih.k1.text")); // NOI18N

        k2.setText(bundle.getString("ViewPemilih.k2.text")); // NOI18N

        k3.setText(bundle.getString("ViewPemilih.k3.text")); // NOI18N

        k4.setText(bundle.getString("ViewPemilih.k4.text")); // NOI18N

        k5.setText(bundle.getString("ViewPemilih.k5.text")); // NOI18N

        k6.setText(bundle.getString("ViewPemilih.k6.text")); // NOI18N

        k7.setText(bundle.getString("ViewPemilih.k7.text")); // NOI18N

        k8.setText(bundle.getString("ViewPemilih.k8.text")); // NOI18N

        k9.setText(bundle.getString("ViewPemilih.k9.text")); // NOI18N

        k10.setText(bundle.getString("ViewPemilih.k10.text")); // NOI18N

        k11.setText(bundle.getString("ViewPemilih.k11.text")); // NOI18N

        fKK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fKK.setText(bundle.getString("ViewPemilih.fKK.text")); // NOI18N

        fNIK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fNIK.setText(bundle.getString("ViewPemilih.fNIK.text")); // NOI18N

        fNama.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fNama.setText(bundle.getString("ViewPemilih.fNama.text")); // NOI18N

        fTTL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fTTL.setText(bundle.getString("ViewPemilih.fTTL.text")); // NOI18N

        fStat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fStat.setText(bundle.getString("ViewPemilih.fStat.text")); // NOI18N

        fRw.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fRw.setText(bundle.getString("ViewPemilih.fRw.text")); // NOI18N

        fJK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fJK.setText(bundle.getString("ViewPemilih.fJK.text")); // NOI18N

        fDukuh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fDukuh.setText(bundle.getString("ViewPemilih.fDukuh.text")); // NOI18N

        fRt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fRt.setText(bundle.getString("ViewPemilih.fRt.text")); // NOI18N

        fUmur.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fUmur.setText(bundle.getString("ViewPemilih.fUmur.text")); // NOI18N

        fDifabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fDifabel.setText(bundle.getString("ViewPemilih.fDifabel.text")); // NOI18N

        javax.swing.GroupLayout panelProfilLayout = new javax.swing.GroupLayout(panelProfil);
        panelProfil.setLayout(panelProfilLayout);
        panelProfilLayout.setHorizontalGroup(
                panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelProfilLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelProfilLayout.createSequentialGroup()
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lTTL)
                                                        .addComponent(lNama)
                                                        .addComponent(lInduk)
                                                        .addComponent(lKK)
                                                        .addComponent(lStatus)
                                                        .addComponent(lJk)
                                                        .addComponent(lDifabel)
                                                        .addGroup(panelProfilLayout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lRT)
                                                                        .addComponent(lDukuh))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelProfilLayout.createSequentialGroup()
                                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(k5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(k1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(k2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(k3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(k4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(k9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(k7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(k6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(fNIK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(fNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(fTTL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(fDukuh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfilLayout.createSequentialGroup()
                                                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(fDifabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                                                                        .addComponent(fJK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(fStat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(fRt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(lUmur)
                                                                                        .addComponent(lRW))
                                                                                .addGap(29, 29, 29)
                                                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(panelProfilLayout.createSequentialGroup()
                                                                                                .addComponent(k11)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(fRw, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(panelProfilLayout.createSequentialGroup()
                                                                                                .addComponent(k10)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(fUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                        .addComponent(fKK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addComponent(k8)))
                                        .addComponent(lAlamat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(panelQR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(panelFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );
        panelProfilLayout.setVerticalGroup(
                panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelProfilLayout.createSequentialGroup()
                                .addComponent(panelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelQR, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(panelProfilLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lKK)
                                        .addComponent(k1)
                                        .addComponent(fKK))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lInduk)
                                        .addComponent(k2)
                                        .addComponent(fNIK))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lNama)
                                        .addComponent(k3)
                                        .addComponent(fNama))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lTTL)
                                        .addComponent(k4)
                                        .addComponent(fTTL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lStatus)
                                        .addComponent(k5)
                                        .addComponent(lUmur)
                                        .addComponent(k10)
                                        .addComponent(fStat)
                                        .addComponent(fUmur))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lJk)
                                        .addComponent(k6)
                                        .addComponent(fJK))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lAlamat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lDukuh)
                                        .addComponent(k7)
                                        .addComponent(fDukuh))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lRT)
                                        .addComponent(k8)
                                        .addComponent(lRW)
                                        .addComponent(k11)
                                        .addComponent(fRt)
                                        .addComponent(fRw))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lDifabel)
                                        .addComponent(k9)
                                        .addComponent(fDifabel))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTPS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("ViewPemilih.panelTPS.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Futured", 1, 12))); // NOI18N

        lProv.setText(bundle.getString("ViewPemilih.lProv.text")); // NOI18N

        fProv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fProv.setText(bundle.getString("ViewPemilih.fProv.text")); // NOI18N

        lKab.setText(bundle.getString("ViewPemilih.lKab.text")); // NOI18N

        fKab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fKab.setText(bundle.getString("ViewPemilih.fKab.text")); // NOI18N

        lKec.setText(bundle.getString("ViewPemilih.lKec.text")); // NOI18N

        fKec.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fKec.setText(bundle.getString("ViewPemilih.fKec.text")); // NOI18N

        lDes.setText(bundle.getString("ViewPemilih.lDes.text")); // NOI18N

        fDes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fDes.setText(bundle.getString("ViewPemilih.fDes.text")); // NOI18N

        lNo.setText(bundle.getString("ViewPemilih.lNo.text")); // NOI18N

        fNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fNo.setText(bundle.getString("ViewPemilih.fNo.text")); // NOI18N

        javax.swing.GroupLayout panelTPSLayout = new javax.swing.GroupLayout(panelTPS);
        panelTPS.setLayout(panelTPSLayout);
        panelTPSLayout.setHorizontalGroup(
                panelTPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTPSLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelTPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelTPSLayout.createSequentialGroup()
                                                .addGroup(panelTPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelTPSLayout.createSequentialGroup()
                                                                .addComponent(lNo)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(fNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(panelTPSLayout.createSequentialGroup()
                                                                .addGroup(panelTPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lProv)
                                                                        .addComponent(lKab)
                                                                        .addComponent(lKec)
                                                                        .addComponent(lDes))
                                                                .addGap(0, 42, Short.MAX_VALUE)))
                                                .addContainerGap())
                                        .addGroup(panelTPSLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(panelTPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(fProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(fKab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(fKec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(fDes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        panelTPSLayout.setVerticalGroup(
                panelTPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTPSLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lProv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fProv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lKab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fKab)
                                .addGap(11, 11, 11)
                                .addComponent(lKec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fKec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lDes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fDes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelTPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lNo)
                                        .addComponent(fNo))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPrint.setText(bundle.getString("ViewPemilih.btnPrint.text")); // NOI18N
        btnPrint.addActionListener(e -> ePrint());

        btnClose.setText(bundle.getString("ViewPemilih.btnClose.text")); // NOI18N
        btnClose.addActionListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(panelProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(panelTPS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnPrint)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnClose)))
                                .addContainerGap())
                        .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(panelProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(panelTPS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnPrint)
                                        .addComponent(btnClose))
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ePrint() {//GEN-FIRST:event_ePrint
        try {
            PrintUtils.printData(pemilih, qr, urut);
        } catch (IOException | PrinterException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_ePrint

    private void loadData(Pemilih p) {
        if (stat == RET_NORMAL) {
            fKK.setText(p.getNoKk());
            fNIK.setText(p.getInduk());
            fNama.setText(p.getNama());
            fTTL.setText(p.getTLahir() + ", " + setTanggal(p.getTglLahir()) + "");
            fStat.setText(p.getStatusCode().toString());
            fUmur.setText(p.getUmur() + "");
            fJK.setText(setJk(p.getJenisKelamin()));
            fDukuh.setText(p.getAlamat());
            fRt.setText(p.getRt());
            fRw.setText(p.getRw());
            fDifabel.setText(p.getDifableCode().toString());
            setTPS(p.getTpsCode());
            setFoto(p.getFoto());
            setQR(setCode(p.getInduk()));
            lTitle.setText("Data " + p.getNama());
        }
    }

    private String setTanggal(java.util.Date d) {
        return StringUtils.setTanggal(d);
    }

    private boolean setFoto(String u) {
        if (u == null) {
            panelFoto.setImage(null);
            return false;
        }
        u = u.replace("address", MainUi.getAppsIp());
        try {
            URL url = new URL(u);
            foto = ImageIO.read(url);
            panelFoto.setImage(foto);
            return true;
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
        return false;
    }

    private boolean setQR(String code) {
        String charset = "UTF-8"; // or "ISO-8859-1"
        Map<EncodeHintType, ErrorCorrectionLevel> hintMap = new EnumMap<>(EncodeHintType.class);
        hintMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);
        try {
            qr = createQR(code, charset, hintMap, 240, 240);
            panelQR.setImage(qr);
            return true;
        } catch (WriterException | IOException ex) {
            Exceptions.printStackTrace(ex);
        }
        return false;
    }

    private BufferedImage createQR(String qrCodeData, String charset, Map<EncodeHintType, ?> hintMap, int qrCodeheight, int qrCodewidth) throws WriterException, IOException {
        BitMatrix matrix = new MultiFormatWriter().encode(new String(qrCodeData.getBytes(charset), charset), BarcodeFormat.QR_CODE, qrCodewidth, qrCodeheight, hintMap);
        return MatrixToImageWriter.toBufferedImage(matrix);
    }

    private String setCode(String s) {
        return new MD5(s).asHex();
    }

    private String setJk(String s) {
        if (s.equals("P")) {
            return "Perempuan";
        }
        return "Laki-Laki";
    }

    private void setTPS(Tps t) {
        fProv.setText(t.getProvCode().toString());
        fKab.setText(t.getKabCode().toString());
        fKec.setText(t.getKecCode().toString());
        fDes.setText(t.getDesCode().toString());
        fNo.setText(t.getNo());
    }

    private void doClose(int retStatus) {
        stat = retStatus;
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel fDes;
    private javax.swing.JLabel fDifabel;
    private javax.swing.JLabel fDukuh;
    private javax.swing.JLabel fJK;
    private javax.swing.JLabel fKK;
    private javax.swing.JLabel fKab;
    private javax.swing.JLabel fKec;
    private javax.swing.JLabel fNIK;
    private javax.swing.JLabel fNama;
    private javax.swing.JLabel fNo;
    private javax.swing.JLabel fProv;
    private javax.swing.JLabel fRt;
    private javax.swing.JLabel fRw;
    private javax.swing.JLabel fStat;
    private javax.swing.JLabel fTTL;
    private javax.swing.JLabel fUmur;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel k1;
    private javax.swing.JLabel k10;
    private javax.swing.JLabel k11;
    private javax.swing.JLabel k2;
    private javax.swing.JLabel k3;
    private javax.swing.JLabel k4;
    private javax.swing.JLabel k5;
    private javax.swing.JLabel k6;
    private javax.swing.JLabel k7;
    private javax.swing.JLabel k8;
    private javax.swing.JLabel k9;
    private javax.swing.JLabel lAlamat;
    private javax.swing.JLabel lDes;
    private javax.swing.JLabel lDifabel;
    private javax.swing.JLabel lDukuh;
    private javax.swing.JLabel lInduk;
    private javax.swing.JLabel lJk;
    private javax.swing.JLabel lKK;
    private javax.swing.JLabel lKab;
    private javax.swing.JLabel lKec;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lNo;
    private javax.swing.JLabel lProv;
    private javax.swing.JLabel lRT;
    private javax.swing.JLabel lRW;
    private javax.swing.JLabel lStatus;
    private javax.swing.JLabel lTTL;
    private javax.swing.JLabel lTitle;
    private javax.swing.JLabel lUmur;
    private com.voting.ui.panel.PanelFoto panelFoto;
    private javax.swing.JPanel panelProfil;
    private com.voting.ui.panel.PanelFoto panelQR;
    private javax.swing.JPanel panelTPS;
    // End of variables declaration//GEN-END:variables

    private int stat = RET_NORMAL;
}
