/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voting.ui.master.dialog;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javax.imageio.ImageIO;

import org.openide.util.Exceptions;

import com.voting.model.master.Calon;
import com.voting.ui.frame.MainUi;

/**
 *
 * @author Rizal
 */
public class ViewCalon extends javax.swing.JDialog implements ActionListener {

    private final ResourceBundle bundle = ResourceBundle.getBundle("com.voting.ui.master.dialog.Bundle");
    BufferedImage foto;
    public static final int RET_NORMAL = 1;
    public static final int RET_CLOSE = 0;

    @Override
    public void actionPerformed(ActionEvent ae) {
        doClose(RET_CLOSE);
    }

    /**
     * Creates new form ViewPemilih
     *
     * @param p
     */
    public ViewCalon() {
        super(MainUi.getInstance(), true);
        initComponents();
    }

    public int setData(Calon c) {
        loadData(c);
        this.setVisible(true);
        return stat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        panelProfil = new javax.swing.JPanel();
        panelFoto = new com.voting.ui.panel.PanelFoto();
        lUrut = new javax.swing.JLabel();
        lInduk = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();
        lJk = new javax.swing.JLabel();
        lAlamat = new javax.swing.JLabel();
        lAgama = new javax.swing.JLabel();
        k1 = new javax.swing.JLabel();
        k2 = new javax.swing.JLabel();
        k3 = new javax.swing.JLabel();
        k4 = new javax.swing.JLabel();
        k5 = new javax.swing.JLabel();
        k6 = new javax.swing.JLabel();
        fUrut = new javax.swing.JLabel();
        fNIK = new javax.swing.JLabel();
        fNama = new javax.swing.JLabel();
        fJK = new javax.swing.JLabel();
        fAlamat = new javax.swing.JLabel();
        fAgama = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(bundle.getString("ViewCalon.title")); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                doClose(RET_CLOSE);
            }
        });

        lTitle.setFont(new java.awt.Font("Futured", 1, 24)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText(bundle.getString("ViewCalon.lTitle.text")); // NOI18N

        panelProfil.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("ViewCalon.panelProfil.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Futured", 1, 12))); // NOI18N

        panelFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout panelFotoLayout = new javax.swing.GroupLayout(panelFoto);
        panelFoto.setLayout(panelFotoLayout);
        panelFotoLayout.setHorizontalGroup(
                panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 110, Short.MAX_VALUE)
        );
        panelFotoLayout.setVerticalGroup(
                panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 148, Short.MAX_VALUE)
        );

        lUrut.setText(bundle.getString("ViewCalon.lUrut.text")); // NOI18N

        lInduk.setText(bundle.getString("ViewCalon.lInduk.text")); // NOI18N

        lNama.setText(bundle.getString("ViewCalon.lNama.text")); // NOI18N

        lJk.setText(bundle.getString("ViewCalon.lJk.text")); // NOI18N

        lAlamat.setText(bundle.getString("ViewCalon.lAlamat.text")); // NOI18N

        lAgama.setText(bundle.getString("ViewCalon.lAgama.text")); // NOI18N

        k1.setText(bundle.getString("ViewCalon.k1.text")); // NOI18N

        k2.setText(bundle.getString("ViewCalon.k2.text")); // NOI18N

        k3.setText(bundle.getString("ViewCalon.k3.text")); // NOI18N

        k4.setText(bundle.getString("ViewCalon.k4.text")); // NOI18N

        k5.setText(bundle.getString("ViewCalon.k5.text")); // NOI18N

        k6.setText(bundle.getString("ViewCalon.k6.text")); // NOI18N

        fUrut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fUrut.setText(bundle.getString("ViewCalon.fUrut.text")); // NOI18N

        fNIK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fNIK.setText(bundle.getString("ViewCalon.fNIK.text")); // NOI18N

        fNama.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fNama.setText(bundle.getString("ViewCalon.fNama.text")); // NOI18N

        fJK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fJK.setText(bundle.getString("ViewCalon.fJK.text")); // NOI18N

        fAlamat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fAlamat.setText(bundle.getString("ViewCalon.fAlamat.text")); // NOI18N

        fAgama.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fAgama.setText(bundle.getString("ViewCalon.fAgama.text")); // NOI18N

        javax.swing.GroupLayout panelProfilLayout = new javax.swing.GroupLayout(panelProfil);
        panelProfil.setLayout(panelProfilLayout);
        panelProfilLayout.setHorizontalGroup(
                panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelProfilLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lNama)
                                        .addComponent(lInduk)
                                        .addComponent(lUrut)
                                        .addComponent(lJk)
                                        .addComponent(lAlamat)
                                        .addComponent(lAgama))
                                .addGap(41, 41, 41)
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelProfilLayout.createSequentialGroup()
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(k2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(k1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(fUrut, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fNIK, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(panelProfilLayout.createSequentialGroup()
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelProfilLayout.createSequentialGroup()
                                                                .addComponent(k6, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfilLayout.createSequentialGroup()
                                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(k5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(k4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(k3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(fNama, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fJK, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(panelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addContainerGap())
        );
        panelProfilLayout.setVerticalGroup(
                panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelProfilLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(panelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addGroup(panelProfilLayout.createSequentialGroup()
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lUrut)
                                                        .addComponent(k1)
                                                        .addComponent(fUrut))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lInduk)
                                                        .addComponent(k2)
                                                        .addComponent(fNIK))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lNama)
                                                        .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(k3)
                                                                .addComponent(fNama)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lJk)
                                                        .addComponent(k4)
                                                        .addComponent(fJK))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lAlamat)
                                                        .addComponent(k5)
                                                        .addComponent(fAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lAgama)
                                                        .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(k6)
                                                                .addComponent(fAgama)))))
                                .addContainerGap())
        );

        btnClose.setText(bundle.getString("ViewCalon.btnClose.text")); // NOI18N
        btnClose.addActionListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnClose)))
                                .addContainerGap())
                        .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClose)
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadData(Calon c) {
        if (stat == RET_NORMAL) {
            fUrut.setText("" + c.getId());
            fNama.setText(c.getNama());
            fNIK.setText(c.getInduk());
            fAgama.setText(c.getAgama());
            fAlamat.setText("<HTML>" + c.getAlamat().replaceAll("\n", "<br/>") + "</HTML>");
            fJK.setText(setJk(c.getJenisKelamin()));
            setFoto(c.getFoto());
            lTitle.setText("Data " + c.getNama());
        }
    }

    private boolean setFoto(String u) {
        if (u == null) {
            panelFoto.setImage(null);
            return false;
        }
        u = u.replace("address", MainUi.getAppsIp());
        try {
            URL url = new URL(u);
            foto = ImageIO.read(url);
            panelFoto.setImage(foto);
            return true;
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
        return false;
    }

    private String setJk(String s) {
        if (s.equals("P")) {
            return "Perempuan";
        }
        return "Laki-Laki";
    }

    private void doClose(int retStatus) {
        stat = retStatus;
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel fAgama;
    private javax.swing.JLabel fAlamat;
    private javax.swing.JLabel fJK;
    private javax.swing.JLabel fNIK;
    private javax.swing.JLabel fNama;
    private javax.swing.JLabel fUrut;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel k1;
    private javax.swing.JLabel k2;
    private javax.swing.JLabel k3;
    private javax.swing.JLabel k4;
    private javax.swing.JLabel k5;
    private javax.swing.JLabel k6;
    private javax.swing.JLabel lAgama;
    private javax.swing.JLabel lAlamat;
    private javax.swing.JLabel lInduk;
    private javax.swing.JLabel lJk;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lTitle;
    private javax.swing.JLabel lUrut;
    private com.voting.ui.panel.PanelFoto panelFoto;
    private javax.swing.JPanel panelProfil;
    // End of variables declaration//GEN-END:variables

    private int stat = RET_NORMAL;
}
